// Code generated by Slice Machine. DO NOT EDIT.

import Collapsible from './Collapsible';
import Image from './Image';
import InteractiveMap from './InteractiveMap';
import Text from './Text';

export {
	Collapsible,
	Image,
	InteractiveMap,
	Text,
};

export const components = {
	collapsible: Collapsible,
	image: Image,
	interactive_map: InteractiveMap,
	text: Text,
};
